# -*- coding: utf-8 -*-
"""Retry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXnnfMOX-0nbFhZjGUCmzkb1wqR3hdTI
"""

def fact(n):
  if n==0:
    return 1
  return n*fact(n-1)

def gamma(n):
  return fact(n-1)

def beta(m,n):
  return(gamma(m)*gamma(n))/gamma(m+n)

beta(2,5)

